// token.cpp
#include "token.hpp"
#include <unordered_map>

static const char *Names[] = {
    "KW_LOOPS_FOR",
    "KW_LOOPS_DO",
    "KW_LOOPS_UNTIL",
    "KW_LOOPS_CONTINUE",
    "KW_FUNC_FUNCTION",
    "KW_FUNC_RETURN",
    "KW_CONDITIONAL_IF",
    "KW_CONDITIONAL_ELSE",
    "KW_CONDITIONAL_ELSEIF",
    "KW_CONDITIONAL_CASEOF",
    "KW_CONDITIONAL_CASE",
    "KW_CONDITIONAL_DEFAULT",
    "KW_WORDBASED_LOGICREL_OPS_AND",
    "KW_WORDBASED_LOGICREL_OPS_OR",
    "KW_WORDBASED_LOGICREL_OPS_NOT",
    "KW_WORDBASED_LOGICREL_OPS_IS",
    "KW_WORDBASED_LOGICREL_OPS_IN",
    "KW_MISC_BREAK",
    "DT_SCALAR",
    "DT_VECTOR",
    "DT_MATRIX",
    "DT_STRING",
    "PUNCTUATION_LBRACE",
    "PUNCTUATION_RBRACE",
    "PUNCTUATION_LPAREN",
    "PUNCTUATION_RPAREN",
    "PUNCTUATION_LBRACKET",
    "PUNCTUATION_RBRACKET",
    "PUNCTUATION_SEMICOLON",
    "PUNCTUATION_ARROW",
    "PUNCTUATION_COMMA",
    "PUNCTUATION_ELLIPSIS",
    "PUNCTUATION_COLON",
    "OPERATORS_STANDARD_PLUSMINUS",
    "OPERATORS_STANDARD_STAR_SLASH_MOD",
    "OPERATORS_MATRIX_TRANSPOSE",
    "OPERATORS_MATRIX_DOT_STAR",
    "OPERATORS_MATRIX_DOT_SLASH",
    "OPERATORS_RELATIONAL_AND_COMPARISON_OPS_LESS",
    "OPERATORS_RELATIONAL_AND_COMPARISON_OPS_GREATER",
    "OPERATORS_RELATIONAL_AND_COMPARISON_OPS_LESS_EQ",
    "OPERATORS_RELATIONAL_AND_COMPARISON_OPS_GREATER_EQ",
    "OPERATORS_ASSIGNMENT",
    "IDENTIFIER",
    "CONSTANTS_BOOL_CONSTANT",
    "CONSTANTS_INT_LITERAL",
    "CONSTANTS_FLOAT_LITERAL",
    "CONSTANTS_STRING_LITERAL",
    "COMPILER_EOF",
    "COMPILER_ERROR",
};


static_assert(sizeof(Names) / sizeof(Names[0]) == NUM_TOKEN_TYPES,
              "Names[] is out of sync with enum TokenType");
              
static const std::unordered_map<std::string, TokenType> KEYWORDS = {
    {"for", KW_LOOPS_FOR},
    {"do", KW_LOOPS_DO},
    {"until", KW_LOOPS_UNTIL},
    {"continue", KW_LOOPS_CONTINUE},
    {"function", KW_FUNC_FUNCTION},
    {"return", KW_FUNC_RETURN},
    {"if", KW_CONDITIONAL_IF},
    {"else", KW_CONDITIONAL_ELSE},
    {"elseif", KW_CONDITIONAL_ELSEIF},
    {"caseof", KW_CONDITIONAL_CASEOF},
    {"case", KW_CONDITIONAL_CASE},
    {"default", KW_CONDITIONAL_DEFAULT},
    {"and", KW_WORDBASED_LOGICREL_OPS_AND},
    {"or", KW_WORDBASED_LOGICREL_OPS_OR},
    {"not", KW_WORDBASED_LOGICREL_OPS_NOT},
    {"is", KW_WORDBASED_LOGICREL_OPS_IS},
    {"in", KW_WORDBASED_LOGICREL_OPS_IN},
    {"break", KW_MISC_BREAK},

    {"i64", DT_SCALAR},
    {"i32", DT_SCALAR},
    {"i16", DT_SCALAR},
    {"f64", DT_SCALAR},
    {"f32", DT_SCALAR},
    {"f16", DT_SCALAR},
    {"bool", DT_SCALAR},

    {"vector", DT_VECTOR},
    {"matrix", DT_MATRIX},
    {"string", DT_STRING},
};

static const std::unordered_map<std::string, TokenType> OPERATORS = {
    {"{", PUNCTUATION_LBRACE},
    {"}", PUNCTUATION_RBRACE},
    {"(", PUNCTUATION_LPAREN},
    {")", PUNCTUATION_RPAREN},
    {"[", PUNCTUATION_LBRACKET},
    {"]", PUNCTUATION_RBRACKET},
    {";", PUNCTUATION_SEMICOLON},
    {"->", PUNCTUATION_ARROW},
    {",", PUNCTUATION_COMMA},
    {"...", PUNCTUATION_ELLIPSIS},
    {":", PUNCTUATION_COLON},

    {"+", OPERATORS_STANDARD_PLUSMINUS},
    {"-", OPERATORS_STANDARD_PLUSMINUS},
    {"*", OPERATORS_STANDARD_STAR_SLASH_MOD},
    {"/", OPERATORS_STANDARD_STAR_SLASH_MOD},
    {"%", OPERATORS_STANDARD_STAR_SLASH_MOD},

    {"'", OPERATORS_MATRIX_TRANSPOSE},
    {".*", OPERATORS_MATRIX_DOT_STAR},
    {"./", OPERATORS_MATRIX_DOT_SLASH},

    {"<", OPERATORS_RELATIONAL_AND_COMPARISON_OPS_LESS},
    {">", OPERATORS_RELATIONAL_AND_COMPARISON_OPS_GREATER},
    {"<=", OPERATORS_RELATIONAL_AND_COMPARISON_OPS_LESS_EQ},
    {">=", OPERATORS_RELATIONAL_AND_COMPARISON_OPS_GREATER_EQ},

    {"=", OPERATORS_ASSIGNMENT},
};

const char *tokenTypeName(TokenType type)
{
    return Names[type];
}

TokenType lookupKeyword(const std::string &lexeme)
{
    auto it = KEYWORDS.find(lexeme);
    return it == KEYWORDS.end() ? IDENTIFIER : it->second;
}

TokenType lookupOperator(const std::string &lexeme)
{
    auto it = OPERATORS.find(lexeme);
    return it == OPERATORS.end() ? COMPILER_ERROR : it->second;
}